[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tichu"
version = "0.0.1"
description = ''
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = []
authors = [{ name = "Nic Dorner", email = "nic.dorner@me.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "tqdm",
    "openai",
    "dotenv",
    "textual>=7.5.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "mypy>=1.0.0",
    "ruff>=0.6.0",
    "types-tqdm>=4.67.3.20260205",
]

[project.urls]
Documentation = "https://github.com/Nic Dorner/tichu#readme"
Issues = "https://github.com/Nic Dorner/tichu/issues"
Source = "https://github.com/Nic Dorner/tichu"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
tichu = ["py.typed"]

[tool.coverage.run]
source_pkgs = ["tichu", "tests"]
branch = true
parallel = true
omit = ["src/tichu/__about__.py"]

[tool.coverage.paths]
tichu = ["src/tichu", "*/tichu/src/tichu"]
tests = ["tests", "*/tichu/tests"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]
